jobs:
  publish-images-for-test-env:
    if: ${{ github.event.label.name == 'ready_to_test' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BRANCH: ${{ github.head_ref }}
        CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
        ORG_NAME: gravitee-io
        REPO_NAME: gravitee-api-management
      name: Trigger publish_docker_images CircleCI workflow
      run: "export JSON_PAYLOAD=\"{ \\\"branch\\\": \\\"${BRANCH}\\\", \\\"parameters\\\
        \": { \\\"gio_action\\\": \\\"publish_docker_images\\\" } }\"\n\necho \"payload\
        \ = $JSON_PAYLOAD\"\ncurl -X POST -d \"${JSON_PAYLOAD}\" \\\n  -H 'Content-Type:\
        \ application/json' -H 'Accept: application/json' -H \"Circle-Token: ${CCI_TOKEN}\"\
        \ \\\n  https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline\
        \ | jq .\n"
name: Publish docker images for test environment
on:
  repository_dispatch:
    types: trigger-ga___publish-images-for-test-env.yml
