jobs:
  remove-ready-to-test-labels:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        ORG_NAME: gravitee-io
        REPO_NAME: gravitee-api-management
      name: Scan pull requests and remove ready_to_test labels
      run: "PR_NUMBERS=$(curl -s -H \"Accept: application/vnd.github.v3+json\" \"\
        https://api.github.com/repos/gravitee-io/gravitee-api-management/issues?state=open&labels=ready_to_test&type=pr\"\
        \ | jq -r '.[].number')\n\nfor PR_NUMBER in $PR_NUMBERS; do\n  # Get all events\
        \ for the PR\n  # Then, filter on \"labeled\" events with \"ready_to_test\"\
        \ label\n  # Get the last time the PR has been labeled with \"ready_to_test\"\
        \n  # Finally, remove the double quotes to be able to parse and compare the\
        \ date\n\n  LAST_TIMESTAMP=$(curl -s \"https://api.github.com/repos/gravitee-io/gravitee-api-management/issues/$PR_NUMBER/events?per_page\\\
        =1000\" | jq '.[] | select(.event == \"labeled\" and .label.name == \"ready_to_test\"\
        ) | .created_at' | tail -n 1 | tr -d '\"')\n  echo \"PR $PR_NUMBER has been\
        \ labeled at $LAST_TIMESTAMP\"\n\n  ONE_WEEK_AGO=$(($(date +%s) - 7*84600))\n\
        \  LAST_TIMESTAMP_EPOCH=$(date -d \"$LAST_TIMESTAMP\" +%s)\n  \n  if [[ $LAST_TIMESTAMP_EPOCH\
        \ -lt ONE_WEEK_AGO ]]; then\n    echo \"The pull request $PR_NUMBER has been\
        \ labeled for more than 1 week, removing the label ready_to_test\"\n    \n\
        \    curl -s -X DELETE \\\n      -H \"Accept: application/vnd.github.v3+json\"\
        \ \\\n      -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \\\n  \
        \    \"https://api.github.com/repos/gravitee-io/gravitee-api-management/issues/$PR_NUMBER/labels/ready_to_test\"\
        \n  fi\ndone\n"
name: Remove ready to test labels
on:
  repository_dispatch:
    types: trigger-ga___remove-ready-to-test-labels.yml
